### ISSUE TITLE
.proto2 - Files instead of .proto3

### ISSUE THREAD

**Issue by B4sti47** [allegro/php-protobuf#103]
Hello,

I want to Create some php classes with .proto - Files of the Version 2, but php-protobuf only works with Version 3 Files.
Is there a workaround to work with .proto 2 Files?

**Comment by hjagodzinski** [comment]
The compiler supports both versions 2 and 3. Can you show code snippet that doesn't work?

**Comment by B4sti47** [comment]
Hello,

I have solved the problem.
But now I Call a generated class in a file and got the Message Class Google/prorobuf/internal/Message Not Found.
Some ideas why?
BR
Basti 

Liebe Grüße 
Bastian Bömerich 


Von meinem iPhone gesendet

**Comment by hjagodzinski** [comment]
Can you show me code example of what you're doing?

**Comment by B4sti47** [comment]
Sure.

I just call the generated .php class which I created out of the .proto files.

```
<?php
namespace tinterface;


require_once 'ApiArray.php';


?>
```

**Comment by hjagodzinski** [comment]
Can you show me your proto file? Do you use project's master branch to compile your proto file?

**Comment by B4sti47** [comment]
Do you have an E-Mail Address?
I don't want to show the file to everybody because it is from an third company

**Comment by hjagodzinski** [comment]
You can send it to hubert.jagodzinski@allegrogroup.com. I'm busy right now I will try to take a look at this shortly.

**Comment by B4sti47** [comment]
Okay, send it.

Thanks and no Problem!

**Comment by FZUPotato** [comment]
i dont know why gdb prompt upd.h is no found.Actually upd.h is included while building php.it is coredump at line 1264 in udp.h(func upb_inttable_lookup32):
UPB_INLINE bool upb_inttable_lookup32(const upb_inttable *t, uint32_t key,
                                      upb_value *v) {
  *v = upb_value_int32(0);  /* Silence compiler warnings. */
  if (key < t->array_size) {                   ----------->here, t is point to a upb_inttable struct,but it's value from 
dispatch = (upb_inttable *) 0x5f4b0fb800000055(dispatch is a odd address,under the MIPS64 architecture, gdb will throw "BUS Error" and generate a coredump).

In my analysis,
upd.h(Line:1264) upb_inttable_lookup32    t = dispatch;
upd.c(Line:9789) int32_t dispatch         upb_inttable *dispatch = d->top->dispatch;
upd.c(Line:9908) size_t run_decoder_vm    memcpy(&d->top->dispatch, d->pc, sizeof(void*));

d->pc is pointed to a static upb_fielddef.maybe a odd address?

**Comment by hjagodzinski** [comment]
@FZUPotato are you sure you posted the comment where you intended to?

**Comment by myggithub** [comment]
@hjagodzinski ,

**Comment by myggithub** [comment]
@hjagodzinski , 
hello,
i follow the steps of readme file, but i get the error:

**Comment by myggithub** [comment]
@hjagodzinski ,
hello,
i follow the steps of readme file, but i got the error:
![image](https://user-images.githubusercontent.com/7836602/29559039-8a0b4950-8760-11e7-80da-8b54fcfa9c8a.png)
the content of foo.proto:
![image](https://user-images.githubusercontent.com/7836602/29559157-dad49602-8760-11e7-9022-d26c84568b1a.png)
Is there a workaround to work with .proto 2 Files? Thank you!

**Comment by hjagodzinski** [comment]
@myggithub I haven't used protobuf for very long time it seems you have installed protobuf with native PHP support (it doesn't support .proto2). The compilation would produce code for native implementation, not for php-protobuf. If you still want to use php-protobuf you need to downgrade protobuf to version < 3.

**Comment by myggithub** [comment]
@hjagodzinski ,thanks your reply!

**Comment by FZUPotato** [comment]
@hjagodzinski ,sorry!I have already delete it.I have the same problem with KalimKaLo.i have already generate php classes, but the class is extend  \Google\Protobuf\Internal\Message? what should i do let the generated class extend from ProtobufMessage like the Bar claess

**Comment by FZUPotato** [comment]
potato@ubuntu:~/php-protobuf$ php protoc-gen-php.php -o ./ test.pro
potato@ubuntu:~/php-protobuf$ cat test.php 
<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.pro

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>test</code>
 */
class test extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 a = 1;</code>
     */
    private $a = 0;

    public function __construct() {
        \GPBMetadata\Test::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 a = 1;</code>
     */
    public function getA()
    {
        return $this->a;
    }

    /**
     * <code>int32 a = 1;</code>
     */
    public function setA($var)
    {
        GPBUtil::checkInt32($var);
        $this->a = $var;
    }

}

**Comment by FZUPotato** [comment]
potato@ubuntu:~/php-protobuf$ php protoc-gen-php.php -o ./ test.pro
potato@ubuntu:~/php-protobuf$ cat test.php 
<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.pro

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>test</code>
 */
class test extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 a = 1;</code>
     */
    private $a = 0;

    public function __construct() {
        \GPBMetadata\Test::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 a = 1;</code>
     */
    public function getA()
    {
        return $this->a;
    }

    /**
     * <code>int32 a = 1;</code>
     */
    public function setA($var)
    {
        GPBUtil::checkInt32($var);
        $this->a = $var;
    }

}

**Comment by FZUPotato** [comment]
`potato@ubuntu:~/php-protobuf$ php protoc-gen-php.php -o ./ test.pro
potato@ubuntu:~/php-protobuf$ cat test.php 
<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.pro

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>test</code>
 */
class test extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 a = 1;</code>
     */
    private $a = 0;

    public function __construct() {
        \GPBMetadata\Test::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 a = 1;</code>
     */
    public function getA()
    {
        return $this->a;
    }

    /**
     * <code>int32 a = 1;</code>
     */
    public function setA($var)
    {
        GPBUtil::checkInt32($var);
        $this->a = $var;
    }

}`

**Comment by FZUPotato** [comment]
potato@ubuntu:~/php-protobuf$ php protoc-gen-php.php -o ./ test.pro
potato@ubuntu:~/php-protobuf$ cat test.php 
<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.pro

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>test</code>
 */
class test extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 a = 1;</code>
     */
    private $a = 0;

    public function __construct() {
        \GPBMetadata\Test::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 a = 1;</code>
     */
    public function getA()
    {
        return $this->a;
    }

    /**
     * <code>int32 a = 1;</code>
     */
    public function setA($var)
    {
        GPBUtil::checkInt32($var);
        $this->a = $var;
    }

}

**Comment by hjagodzinski** [comment]
@FZUPotato no problem :) It means you use protoc having native PHP support. Take a look at my previous answer. That problem is somewhat related yo yours.

**Comment by FZUPotato** [comment]
![1](https://user-images.githubusercontent.com/31136251/29666678-ec95c8c8-890b-11e7-8342-f2cb2ffce73c.png)

**Comment by FZUPotato** [comment]
i need to downgrade protobuf to version < 3? But my proc file is proto3, it can generate php class with proto3 file under version protoc version 2.X?

**Comment by FZUPotato** [comment]
I need to downgrade protobuf to version < 3? But my proto file is proto3,Does it works?
