### ISSUE TITLE
A Problem occured When Using protoc-gen-php.php

### ISSUE THREAD

**Issue by rocketsryf** [allegro/php-protobuf#106]
I use command php protoc-gen-php.php foo.proto
Then show me following content
ERROR: Unable to parse a message passed by protoc. : parse error - "'span' field wire type is length-delimited but should be varint"

I do not konw what does the error mean;

**Comment by hjagodzinski** [comment]
Take a look at #98.

**Comment by rocketsryf** [comment]
@hjagodzinski ,thank you
another question:
--php_out: protoc-gen-php: Plugin output is unparseable: This is a stub file for IDEs, don\'t use it directly!
what does it mean?

**Comment by hjagodzinski** [comment]
You welcome! It means you have included this file https://github.com/allegro/php-protobuf/blob/master/stubs/ProtobufMessage.php. You should not when running your code. You should have installed a module instead.
