### ISSUE TITLE
undefined method Foo::setBar() 

### ISSUE THREAD

**Issue by jLynx** [allegro/php-protobuf#107]
Hi all, I am getting this problem when I use the demo code given in the readme:

```
require_once 'Foo.php';

$foo = new Foo();
$foo->setBar(1);
$foo->setBaz('two');
$foo->appendSpam(3.0);
$foo->appendSpam(4.0);

```

Call to undefined method Foo::setBar() in C:\WebServer\.....removed......\test.php on line 6

I am running this in Windows Server 2012 R2 with PHP version 5.6

**Comment by roukmoute** [comment]
Because `setBar` is undefined?
Send all the necessary, here `Foo` class.
