### ISSUE TITLE
--php_out: protoc-gen-php: Plugin failed with status code 127.

### ISSUE THREAD

**Issue by fucan** [allegro/php-protobuf#111]
hello everybody
when i put this command
php protoc-gen-php.php vote.proto 
i got this error

: No such file or directory
--php_out: protoc-gen-php: Plugin failed with status code 127.
ERROR: protoc exited with an exit status 1 when executed with: 
  protoc \
    --plugin=protoc-gen-php='/mnt/hgfs/E/personalgit/php-protobuf/protoc-gen-php.php' \
    --php_out=':./' \
    'foo.proto'

and what should i do???  thank you!

**Comment by wjq310** [comment]
请问这个处理好了吗？我遇到了一样的问题

**Comment by qisenshi** [comment]
I have the same problem , and what should i do??? thank you!

**Comment by hjagodzinski** [comment]
`protoc-gen-php.php` requires protoc to be installed. Do you have it installed?
