### ISSUE TITLE
generate syntax error php code for nested group proto

### ISSUE THREAD

**Issue by jueljust** [allegro/php-protobuf#113]
# run command

	# php protoc-gen-php.php pbdata.proto
	PHP Notice:  Undefined offset: 10 in /opt/proto/php-protobuf/src/Allegro/Protobuf/Compiler/FieldDescriptor.php on line 129
	PHP Stack trace:
	PHP   1. {main}() /opt/proto/php-protobuf/protoc-gen-php.php:0
	PHP   2. Allegro\Protobuf\Compiler\Compiler->run() /opt/proto/php-protobuf/protoc-gen-php.php:34
	PHP   3. Allegro\Protobuf\Compiler\PhpGenerator->generate() /opt/proto/php-protobuf/src/Allegro/Protobuf/Compiler/Compiler.php:29
	PHP   4. Allegro\Protobuf\Compiler\PhpGenerator->_generateFiles() /opt/proto/php-protobuf/src/Allegro/Protobuf/Compiler/PhpGenerator.php:59
	PHP   5. Allegro\Protobuf\Compiler\PhpGenerator->_createClass() /opt/proto/php-protobuf/src/Allegro/Protobuf/Compiler/PhpGenerator.php:303
	PHP   6. Allegro\Protobuf\Compiler\PhpGenerator->_createClass() /opt/proto/php-protobuf/src/Allegro/Protobuf/Compiler/PhpGenerator.php:321
	PHP   7. Allegro\Protobuf\Compiler\PhpGenerator->_createClassConstructor() /opt/proto/php-protobuf/src/Allegro/Protobuf/Compiler/PhpGenerator.php:350
	PHP   8. Allegro\Protobuf\Compiler\FieldDescriptor->getScalarInternalType() /opt/proto/php-protobuf/src/Allegro/Protobuf/Compiler/PhpGenerator.php:787
	PHP Notice:  Undefined offset: 10 in /opt/proto/php-protobuf/src/Allegro/Protobuf/Compiler/FieldDescriptor.php on line 129
	PHP Stack trace:
	PHP   1. {main}() /opt/proto/php-protobuf/protoc-gen-php.php:0
	PHP   2. Allegro\Protobuf\Compiler\Compiler->run() /opt/proto/php-protobuf/protoc-gen-php.php:34
	PHP   3. Allegro\Protobuf\Compiler\PhpGenerator->generate() /opt/proto/php-protobuf/src/Allegro/Protobuf/Compiler/Compiler.php:29
	PHP   4. Allegro\Protobuf\Compiler\PhpGenerator->_generateFiles() /opt/proto/php-protobuf/src/Allegro/Protobuf/Compiler/PhpGenerator.php:59
	PHP   5. Allegro\Protobuf\Compiler\PhpGenerator->_createClass() /opt/proto/php-protobuf/src/Allegro/Protobuf/Compiler/PhpGenerator.php:303
	PHP   6. Allegro\Protobuf\Compiler\PhpGenerator->_createClassConstructor() /opt/proto/php-protobuf/src/Allegro/Protobuf/Compiler/PhpGenerator.php:350
	PHP   7. Allegro\Protobuf\Compiler\FieldDescriptor->getScalarInternalType() /opt/proto/php-protobuf/src/Allegro/Protobuf/Compiler/PhpGenerator.php:787

# proto file

	syntax = "proto2";
	package pbdata;

	message ValueType {
		optional int32 int_type =1;
		optional int64 long_type = 2;
		optional float float_type = 3;
		optional string string_type =4;
	}

	message Log {
		required int64 log_timestamp =1;
		optional string ip = 2;
		optional group Field  = 3 {
			repeated group Map = 1 {
				required string key = 1;
				optional ValueType value = 2;
			}
		}
	}

# generated 4 php files
* Log_Field_Map.php  
* Log_Field.php  
* Log.php  
* ValueType.php

# Log.php having syntax error
    

	<?php
	/**
	 * Auto generated from pbdata.proto at 2018-02-04 20:15:39
	 *
	 * pbdata package
	 */

	namespace Pbdata {
	/**
	 * Log message
	 */
	class Log extends \ProtobufMessage
	{
		/* Field index constants */
		const LOG_TIMESTAMP = 1;
		const IP = 2;
		const FIELD = 3;

		/* @var array Field descriptors */
		protected static $fields = array(
			self::LOG_TIMESTAMP => array(
				'name' => 'log_timestamp',
				'required' => true,
				'type' => \ProtobufMessage::PB_TYPE_INT,
			),
			self::IP => array(
				'name' => 'ip',
				'required' => false,
				'type' => \ProtobufMessage::PB_TYPE_STRING,
			),
			self::FIELD => array(
				'name' => 'field',
				'required' => false,
				'type' => ,
			),
		);

		/**
		 * Constructs new message container and clears its internal state
		 */
		public function __construct()
		{
			$this->reset();
		}

		/**
		 * Clears message values and sets default ones
		 *
		 * @return null
		 */
		public function reset()
		{
			$this->values[self::LOG_TIMESTAMP] = null;
			$this->values[self::IP] = null;
			$this->values[self::FIELD] = null;
		}

		/**
		 * Returns field descriptors
		 *
		 * @return array
		 */
		public function fields()
		{
			return self::$fields;
		}

		/**
		 * Sets value of 'log_timestamp' property
		 *
		 * @param integer $value Property value
		 *
		 * @return null
		 */
		public function setLogTimestamp($value)
		{
			return $this->set(self::LOG_TIMESTAMP, $value);
		}

		/**
		 * Returns value of 'log_timestamp' property
		 *
		 * @return integer
		 */
		public function getLogTimestamp()
		{
			$value = $this->get(self::LOG_TIMESTAMP);
			return $value === null ? (integer)$value : $value;
		}

		/**
		 * Sets value of 'ip' property
		 *
		 * @param string $value Property value
		 *
		 * @return null
		 */
		public function setIp($value)
		{
			return $this->set(self::IP, $value);
		}

		/**
		 * Returns value of 'ip' property
		 *
		 * @return string
		 */
		public function getIp()
		{
			$value = $this->get(self::IP);
			return $value === null ? (string)$value : $value;
		}

		/**
		 * Sets value of 'field' property
		 *
		 * @param  $value Property value
		 *
		 * @return null
		 */
		public function setField($value)
		{
			return $this->set(self::FIELD, $value);
		}

		/**
		 * Returns value of 'field' property
		 *
		 * @return
		 */
		public function getField()
		{
			$value = $this->get(self::FIELD);
			return $value === null ? ()$value : $value;
		}
	}
	}

# Log_Field.php having syntax error

	<?php
	/**
	 * Auto generated from pbdata.proto at 2018-02-04 20:15:39
	 *
	 * pbdata package
	 */

	namespace Pbdata {
	/**
	 * Field message embedded in Log message
	 */
	class Log_Field extends \ProtobufMessage
	{
		/* Field index constants */
		const MAP = 1;

		/* @var array Field descriptors */
		protected static $fields = array(
			self::MAP => array(
				'name' => 'map',
				'repeated' => true,
				'type' => ,
			),
		);

		/**
		 * Constructs new message container and clears its internal state
		 */
		public function __construct()
		{
			$this->reset();
		}

		/**
		 * Clears message values and sets default ones
		 *
		 * @return null
		 */
		public function reset()
		{
			$this->values[self::MAP] = array();
		}

		/**
		 * Returns field descriptors
		 *
		 * @return array
		 */
		public function fields()
		{
			return self::$fields;
		}

		/**
		 * Appends value to 'map' list
		 *
		 * @param  $value Value to append
		 *
		 * @return null
		 */
		public function appendMap($value)
		{
			return $this->append(self::MAP, $value);
		}

		/**
		 * Clears 'map' list
		 *
		 * @return null
		 */
		public function clearMap()
		{
			return $this->clear(self::MAP);
		}

		/**
		 * Returns 'map' list
		 *
		 * @return []
		 */
		public function getMap()
		{
			return $this->get(self::MAP);
		}

		/**
		 * Returns 'map' iterator
		 *
		 * @return \ArrayIterator
		 */
		public function getMapIterator()
		{
			return new \ArrayIterator($this->get(self::MAP));
		}

		/**
		 * Returns element from 'map' list at given offset
		 *
		 * @param int $offset Position in list
		 *
		 * @return
		 */
		public function getMapAt($offset)
		{
			return $this->get(self::MAP, $offset);
		}

		/**
		 * Returns count of 'map' list
		 *
		 * @return int
		 */
		public function getMapCount()
		{
			return $this->count(self::MAP);
		}
	}
	}

# Log_Field_Map.php

	<?php
	/**
	 * Auto generated from pbdata.proto at 2018-02-04 20:15:39
	 *
	 * pbdata package
	 */

	namespace Pbdata {
	/**
	 * Map message embedded in Field/Log message
	 */
	class Log_Field_Map extends \ProtobufMessage
	{
		/* Field index constants */
		const KEY = 1;
		const VALUE = 2;

		/* @var array Field descriptors */
		protected static $fields = array(
			self::KEY => array(
				'name' => 'key',
				'required' => true,
				'type' => \ProtobufMessage::PB_TYPE_STRING,
			),
			self::VALUE => array(
				'name' => 'value',
				'required' => false,
				'type' => '\Pbdata\ValueType'
			),
		);

		/**
		 * Constructs new message container and clears its internal state
		 */
		public function __construct()
		{
			$this->reset();
		}

		/**
		 * Clears message values and sets default ones
		 *
		 * @return null
		 */
		public function reset()
		{
			$this->values[self::KEY] = null;
			$this->values[self::VALUE] = null;
		}

		/**
		 * Returns field descriptors
		 *
		 * @return array
		 */
		public function fields()
		{
			return self::$fields;
		}

		/**
		 * Sets value of 'key' property
		 *
		 * @param string $value Property value
		 *
		 * @return null
		 */
		public function setKey($value)
		{
			return $this->set(self::KEY, $value);
		}

		/**
		 * Returns value of 'key' property
		 *
		 * @return string
		 */
		public function getKey()
		{
			$value = $this->get(self::KEY);
			return $value === null ? (string)$value : $value;
		}

		/**
		 * Sets value of 'value' property
		 *
		 * @param \Pbdata\ValueType $value Property value
		 *
		 * @return null
		 */
		public function setValue(\Pbdata\ValueType $value=null)
		{
			return $this->set(self::VALUE, $value);
		}

		/**
		 * Returns value of 'value' property
		 *
		 * @return \Pbdata\ValueType
		 */
		public function getValue()
		{
			return $this->get(self::VALUE);
		}
	}
	}

# Value_Type.php

	<?php
	/**
	 * Auto generated from pbdata.proto at 2018-02-04 20:15:39
	 *
	 * pbdata package
	 */

	namespace Pbdata {
	/**
	 * ValueType message
	 */
	class ValueType extends \ProtobufMessage
	{
		/* Field index constants */
		const INT_TYPE = 1;
		const LONG_TYPE = 2;
		const FLOAT_TYPE = 3;
		const STRING_TYPE = 4;

		/* @var array Field descriptors */
		protected static $fields = array(
			self::INT_TYPE => array(
				'name' => 'int_type',
				'required' => false,
				'type' => \ProtobufMessage::PB_TYPE_INT,
			),
			self::LONG_TYPE => array(
				'name' => 'long_type',
				'required' => false,
				'type' => \ProtobufMessage::PB_TYPE_INT,
			),
			self::FLOAT_TYPE => array(
				'name' => 'float_type',
				'required' => false,
				'type' => \ProtobufMessage::PB_TYPE_FLOAT,
			),
			self::STRING_TYPE => array(
				'name' => 'string_type',
				'required' => false,
				'type' => \ProtobufMessage::PB_TYPE_STRING,
			),
		);

		/**
		 * Constructs new message container and clears its internal state
		 */
		public function __construct()
		{
			$this->reset();
		}

		/**
		 * Clears message values and sets default ones
		 *
		 * @return null
		 */
		public function reset()
		{
			$this->values[self::INT_TYPE] = null;
			$this->values[self::LONG_TYPE] = null;
			$this->values[self::FLOAT_TYPE] = null;
			$this->values[self::STRING_TYPE] = null;
		}

		/**
		 * Returns field descriptors
		 *
		 * @return array
		 */
		public function fields()
		{
			return self::$fields;
		}

		/**
		 * Sets value of 'int_type' property
		 *
		 * @param integer $value Property value
		 *
		 * @return null
		 */
		public function setIntType($value)
		{
			return $this->set(self::INT_TYPE, $value);
		}

		/**
		 * Returns value of 'int_type' property
		 *
		 * @return integer
		 */
		public function getIntType()
		{
			$value = $this->get(self::INT_TYPE);
			return $value === null ? (integer)$value : $value;
		}

		/**
		 * Sets value of 'long_type' property
		 *
		 * @param integer $value Property value
		 *
		 * @return null
		 */
		public function setLongType($value)
		{
			return $this->set(self::LONG_TYPE, $value);
		}

		/**
		 * Returns value of 'long_type' property
		 *
		 * @return integer
		 */
		public function getLongType()
		{
			$value = $this->get(self::LONG_TYPE);
			return $value === null ? (integer)$value : $value;
		}

		/**
		 * Sets value of 'float_type' property
		 *
		 * @param double $value Property value
		 *
		 * @return null
		 */
		public function setFloatType($value)
		{
			return $this->set(self::FLOAT_TYPE, $value);
		}

		/**
		 * Returns value of 'float_type' property
		 *
		 * @return double
		 */
		public function getFloatType()
		{
			$value = $this->get(self::FLOAT_TYPE);
			return $value === null ? (double)$value : $value;
		}

		/**
		 * Sets value of 'string_type' property
		 *
		 * @param string $value Property value
		 *
		 * @return null
		 */
		public function setStringType($value)
		{
			return $this->set(self::STRING_TYPE, $value);
		}

		/**
		 * Returns value of 'string_type' property
		 *
		 * @return string
		 */
		public function getStringType()
		{
			$value = $this->get(self::STRING_TYPE);
			return $value === null ? (string)$value : $value;
		}
	}
	}

**Comment by hjagodzinski** [comment]
The groups are not supported. A few years back when this project was initially developed the groups were already deprecated.

The error message should be more verbose though.

**Comment by hjagodzinski** [comment]
I've changed the generator in a way it ignores the groups outputting a warning to a console and I've added a 'Know issues' section so it's clear from the start which parts of protocol buffers are not supported.
