### ISSUE TITLE
Module version number incorrect

### ISSUE THREAD

**Issue by idoru** [allegro/php-protobuf#114]
Hi,

we just started using 0.12.0 today and noticed that php_info returns 0.11.0 for the protobuf extension.

Seems like this is due to this not being updated: https://github.com/allegro/php-protobuf/blob/ebb10426b7449db88eb40e1a092b5073d52d177d/php_protobuf.h

**Comment by hjagodzinski** [comment]
Hi,

Shit, you're right, I missed that altogether. I've created a new release with fixed version information.
