### ISSUE TITLE
how to use php-probuf with this .proto file 

### ISSUE THREAD

**Issue by korangu** [allegro/php-protobuf#117]
hi i am new to protocol buffer i don't know how to use php-protobuf for this file

https://github.com/yeriomin/play-store-api/blob/master/src/main/proto/GooglePlay.proto

i already installed the requirements 

please help

**Comment by hjagodzinski** [comment]
Hi,

Unfortunately the proto file contains groups which are no supported by this project (groups were already deprecated at the time this project started 6 years ago).

[Getting started](https://github.com/allegro/php-protobuf#getting-started) is a good point to get your hands dirty.
