### ISSUE TITLE
How to generate the CodeGeneratorResponse.php file?

### ISSUE THREAD

**Issue by lovepurple** [allegro/php-protobuf#118]
I want custom a generator ,but i cant find any solution to generate the codegeneratorresponse from complier/plugin.proto ?

**Comment by hjagodzinski** [comment]
You can use any available implementation to compile plugin.proto in a way you desire. You can use this project by adjusting a code generation.

**Comment by lovepurple** [comment]
Thanks @hjagodzinski !
