### ISSUE TITLE
Why change null to another value?

### ISSUE THREAD

**Issue by bingxuecandong** [allegro/php-protobuf#126]
Sorry, my English is bad.

in file PhpGenerator.php line 711.

[https://github.com/allegro/php-protobuf/blob/master/src/Allegro/Protobuf/Compiler/PhpGenerator.php#L711](https://github.com/allegro/php-protobuf/blob/master/src/Allegro/Protobuf/Compiler/PhpGenerator.php#L711)

`'return $value === null ? ' . $returnCast . '$value : $value;'`

Why change null to another value?

Is this a bug?

I think this may be more reasonable.

`'return $value !== null ? ' . $returnCast . '$value : $value;'`

**Comment by hjagodzinski** [comment]
I'm not able to answer your question why it's done this way (this code was written years ago). I can say though, how I would approach it today. The most reasonable approach boils down to:

```PHP
'return $value;'
```

Why? Firstly `$value` has proper type if a value is set therefore no need to type casting. Secondly `null` directly informs you that the value was not set.

Nevertheless changing this would break the established contract. It would need to be introduced with a way to preserve backward-compatibility for those who already rely on it.

**Comment by hjagodzinski** [comment]
It has turned out I should be able to remember why null values are cast 😄 [Here](#91) you can find a discussion that lead to this change. The bottom line is it works with accordance with official Google's guideline and hence won't be changed.

**Comment by hjagodzinski** [comment]
@bingxuecandong in the latest release I have added generation of *has* methods which you can use to check whether a field is set.
