### ISSUE TITLE
ERROR: Unable to find the protoc command. Please make sure it's installed and available in the path.

### ISSUE THREAD

**Issue by lifewahaha** [allegro/php-protobuf#128]
Hello,
    I install the protobuf.so crrectly but there have a error when run the command below:
`[root@mail php-protobuf]# php -m
[PHP Modules]
apcu
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
igbinary
json
libxml
mbstring
mcrypt
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
protobuf
readline
redis
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zip
zlib

[Zend Modules]

[root@mail php-protobuf]# php protoc-gen-php.php foo.proto
sh: protoc: command not found
ERROR: Unable to find the protoc command. Please make sure it's installed and available in the path.
`
Could you please help me figure out it?
Thank you.

**Comment by hjagodzinski** [comment]
Hi @lifewahaha,

Please make sure you have installed [protocol buffers](https://github.com/protocolbuffers/protobuf) which comes with `protoc` command and that `protoc` is available on the `$PATH`.
