### ISSUE TITLE
How do we send request and receive response with this?

### ISSUE THREAD

**Issue by codeitlikemiley** [allegro/php-protobuf#133]
Do i need additional package to be able to make an http request  
anyone can help me?

Im using laravel , with this, php-protobuf, i already manage to compile proto file to php files
but Im puzzle what to use when sending request 
Hope someone can clarify this to me thanks

**Comment by JackNoordhuis** [comment]
From the readme: `Protocol Buffers are a way of encoding structured data in an efficient yet extensible format. It might be used in file formats and RPC protocols.`

Unless you somehow plan on implementing the http protocol with protobuf this extension probably isn't what you're looking for if you're only writing a laravel web app.
