### ISSUE TITLE
Can't be compiled for > PHP 7 on Windows 7 x64

### ISSUE THREAD

**Issue by bcashier** [allegro/php-protobuf#134]
Hi

I am unable to compile it for:
- PHP 7.4.3
- PHP 7.2.28

I am getting this error message:

```
The system cannot find the file specified (php_protobuf.dll.res).
NMAKE : fatal error U1077: 'rc' : return code '0x1'
Stop.
```

**Comment by Bee777** [comment]
I have encountered the same issue but i have fixes by remove the angle brackets **< >** in the **CREDITS** file at mentioned in [https://phabricator.wikimedia.org/T208660](url)
and this is the built **dll** file for **[php7.3 Thread Safe (TS) x64](https://1drv.ms/u/s!AsxMWpXIvJIzjmHLhX5yfKOmMZLW?e=MbmEIM)**

**Comment by xiao199306** [comment]
> @bcashier
> 
> I have encountered the same issue but i have fix it by remove the angle brackets **< >** in the **CREDITS** file at happens in [https://phabricator.wikimedia.org/T208660](url)
> and this is the built **dll** file for **[php7.3 Thread Safe (TS) x64](https://1drv.ms/u/s!AsxMWpXIvJIzjmHLhX5yfKOmMZLW?e=MbmEIM)**
> 
> **For who want to know how to install the extension:**
> 
> > instruction: [https://stackoverflow.com/a/58551223/8503381](url)
> 
> 1. Copy both php7.dll and php_protobuf.dll to System32.
> 2. Run a command prompt as Admin and navigate to C:\Windows\System32 and execute the command **regsvr32 php_protobuf.dll** then you will get a message that **the DLL was loaded but entry point was not found**.
> 3. Copy **php_protobuf.dll** to ext folder under the XAMPP php folder.
> 4. Also add **extension=php_protobuf.dll** to **php.ini** file.
> 5. Try to run **php --ini** if it works you will get no warning message.


hello Do you have  php_protobuf.dll

**Comment by xiao199306** [comment]
I have the same problem now，PHP 5.6 on Windows 10 x64  Do you know how to install it . think you

**Comment by Bee777** [comment]
> I have the same problem now，PHP 5.6 on Windows 10 x64 Do you know how to install it . think you

Yes i have, but it's for PHP 7.3 as in the link,
To install you can read the instruction that i have mentioned above.
