### ISSUE TITLE
one question --php_out: protoc-gen-php: Plugin output is unparseable: This is a stub file for IDEs, don't use it directly!

### ISSUE THREAD

**Issue by Machine03** [allegro/php-protobuf#136]
devtools:MacOS, PHP7.3 protoc 3.13
question:
protoc --plugin=protoc-gen-allegrophp=protoc-gen-php.php --allegrophp_out='./' movie.proto

the message : --php_out: protoc-gen-php: Plugin output is unparseable: This is a stub file for IDEs, don't use it directly!
#106 I don't understand what can i do, please tell me more detail thanks.

**Comment by hjagodzinski** [comment]
[ProtobufMessage.php](https://github.com/allegro/php-protobuf/blob/master/stubs/ProtobufMessage.php) is not referenced from php-protobuf source. If you see this error message it means `ProtobufMessage.php` gets included by your environment when running php process. Make sure this file is not included.
