### ISSUE TITLE
Getting Fatal error: Class 'ProtobufMessage' not found in /home/ashwinn/public_html/php-protobuf/example/pb_proto_foo.php on line 10 when trying to execute from browser

### ISSUE THREAD

**Issue by ashwinnasare** [allegro/php-protobuf#16]

**Comment by enumag** [comment]
I'm getting the same problem. phpinfo reports that file `/etc/php/7.2/cli/conf.d/20-protobuf.ini` was loaded and the file contains `extensions=protobuf.so`. But still I'm getting `Fatal error: Class 'ProtobufMessage' not found`. Why?

**Comment by hjagodzinski** [comment]
@enumag make sure you placed `protobuf.so` in a directory where PHP looks up for extensions. You can find this directory by running command:
```bash
$ php-config --extension-dir
```

**Comment by enumag** [comment]
... Ok I found the problem. My protobuf.ini contained `extensions=protobuf.so` instead of `extension=protobuf.so`.
