### ISSUE TITLE
Integrate with Protobuf-PHP

### ISSUE THREAD

**Issue by drslump** [allegro/php-protobuf#17]
I'm the author of [Protobuf-PHP](https://github.com/drslump/Protobuf-PHP) and I would like to propose you to merge both projects.

To be honest, the main motivation on my part is that I'm no longer doing PHP development, so maintaining the library has become a low-priority task for me. It'll be great if both projects could be merged to offer a great solution for Protobuf under PHP. 

About two years ago I integrated a C extension for parsing the protobuf binary format (the **lazy branch** on the repo), since we needed some additional performance in a project. That change forced some refactorings and several optimizations to the PHP code too. It should be fairly easy to include support for your C extension.

As I see it, both projects have strong points going for them, *php-protobuf* must be really fast by having the runtime completely implemented in C, while *protobuf-php* hooks into the `protoc` command as a plugin to make use of its compiler, can work without extensions and allows to use other formats (ie: json, xml).

What do you think?

**Comment by g1111111g** [comment]
good job
