### ISSUE TITLE
Syntax error required uint32 Time=1;

### ISSUE THREAD

**Issue by sidealice** [allegro/php-protobuf#25]
<pre>
message Log{
	required uint32 Time=1;
	message Content{
		required string Key=1;
		required string Value=2;
	}
	repeated Content Contents=2;
}
message LogGroup{
	repeated Log Logs=1;
	required string Category=2;
	optional string Topic=3;
	optional string Source=4;
}
</pre>

don't know why it throw the error..

**Comment by eancc** [comment]
hi, In the file "ProtobufCompiler/ProtobufParser.php" replace 983 line codes  :
[\s]+([^;^=^\s]+)[\s]+=[\s]+([\d]+);/     =>  [\s]+([^;^=^\s]+)[\s]{0,}=[\s]{0,}([\d]+);/

**Comment by hjagodzinski** [comment]
Hi eancc,

If you've found the source of the issue, please pull request it so other can benefit from it.

**Comment by hjagodzinski** [comment]
Fixed in #74.
