### ISSUE TITLE
How to change a value in a repeated item

### ISSUE THREAD

**Issue by shiningstarpxx** [allegro/php-protobuf#30]
1 message UserItem
  2 {
  3     repeated int32 nums = 1;
  4 }
  5 
  6 message User
  7 {
  8     repeated int32 data = 1;
  9     optional UserItem item = 2;
 10 }

for example, 

12 include('pb_proto_test.php');
 13 
 14 $u = new User();
 15 
 16 for($i=0; $i<2; $i++ )
 17 {
 18     $u->appendData($i);
 19 }
 20 echo $u->getDataAt(1)."\n"; // 0
 21 echo $u->getDataAt(0)."\n"; // 1

 34 $d = $u->getDataIterator();
 
 36 $d->offsetSet(1, 100); // want to change data[1] = 100;
 37 var_dump($d);           // d is object, has array( 0=>0, 1=>100)
 39 var_dump($u->getData());  // but u has not been changed?

if I want to change a item's value in a repeated field, what should i do?

**Comment by hjagodzinski** [comment]
Unfortunately generated message class doesn't provide any way to do it. The possible solution would be a getter/setter method pair. This way you have full PHP's arsenal at you disposal to work with an array.
