### ISSUE TITLE
I get the following error when trying to compile a proto, error '[packed=true]'

### ISSUE THREAD

**Issue by hail812** [allegro/php-protobuf#31]
ERROR:
Syntax error repeated int32 excluded_product_category = 19 [packed=true];

PROTO:
repeated int32 excluded_product_category = 19 [packed=true];

**Comment by hail812** [comment]
which version of google-protobuf ?

**Comment by axxapy** [comment]
Hi guys.
Is there a support for [packed=true] repeatable fields?

**Comment by hjagodzinski** [comment]
No, repeated packed fields are not supported.

**Comment by PunitSaharan** [comment]
Hi please help me i want to install php-protobuf in xamp on window.but i have no idea how it will be installed .when i run protoc-php.php its show "requires protobuf extension installed to run". how can i install this extension ??

Thanks

**Comment by hjagodzinski** [comment]
The repeated packed fields are [#74](now supported).
