### ISSUE TITLE
Problem with recursive types

### ISSUE THREAD

**Issue by dnet** [allegro/php-protobuf#34]
The compiler cannot handle when a type has a member of its own type, thus it's impossible to represent nested (tree-like) structures, while [Protocol Buffers allow this](https://groups.google.com/forum/#!msg/protobuf/RXYno--3R18/kqdeTrnyRu0J).

Error message:

    PHP Notice:  Undefined index: XXX in /path/to/php-protobuf/ProtobufCompiler/ProtobufParser.php
    Type XXX not defined

Relevant excerpt from proto file:

    message XXX {
        optional uint32 somedata = 1;
        repeated XXX children = 2;
    }

**Comment by hjagodzinski** [comment]
Fixed in #74.
