### ISSUE TITLE
Add support for the new proto3 syntax

### ISSUE THREAD

**Issue by mikehedman** [allegro/php-protobuf#39]
Currently it looks like the library supports the proto2 syntax, but Google is suggesting that new projects should start out using proto3.
https://developers.google.com/protocol-buffers/docs/proto3

**Comment by fjjiaboming** [comment]
*_*  waiting

**Comment by cuonic** [comment]
+1

**Comment by fjjiaboming** [comment]
+1
We need it , too!

**Comment by jim01** [comment]
Sounds like this might be what I need. 

Trying to compile this proto is not going so well https://raw.githubusercontent.com/mapbox/vector-tile-spec/master/1.0.1/vector_tile.proto

**Comment by Shumkov** [comment]
:+1:

**Comment by fangzz** [comment]
+1
Would be awesome.

**Comment by ikandars** [comment]
+1

**Comment by hjagodzinski** [comment]
Resolved in #74.
