### ISSUE TITLE
Windows Binary

### ISSUE THREAD

**Issue by olekukonko** [allegro/php-protobuf#4]
Thanks a lot for the library. Any plans  for windows support ?

**Comment by Gielert** [comment]
I have compiled the binaries to both thread safe and non-thread safe. I don't know if you still need them but here they are anyway.

https://www.dropbox.com/s/3d9g9ozxq0z9h3x/php-protobuf_x86.zip?dl=0

Binaries are compiled for PHP 5.6 x86

Here's the virustotal:
https://www.virustotal.com/en/file/22be40d7acb4eb43a4a14205d68726bba4e6de66a367f65566029d349e365825/analysis/1451938893/

SHA256: 22be40d7acb4eb43a4a14205d68726bba4e6de66a367f65566029d349e365825

**Comment by Zhang44444** [comment]
@Gielert I had compiled for PHP 7.0 x86. But I failed. Could you give me some advice or give me compiled  binary. Thank you.
