### ISSUE TITLE
Can't compile file with own enum type

### ISSUE THREAD

**Issue by davel2k** [allegro/php-protobuf#45]
When I try to compile this enum type and message

    enum EJobStatus {
        WAITING = 0;
        RUNNING = 1;
        FINISHED = 2;
    };

    message MJobs {
        optional string name = 1;
        optional EJobStatus status = 2;
    }

I get this error:
    
    php php-protobuf/protoc-php.php MJobs.proto
    *Proto file missformed*

**Comment by rotencode** [comment]
this error happens due to your wrong char ';' at the end of enum.

`enum EJobStatus {
    WAITING = 0;
    RUNNING = 1;
    FINISHED = 2;
}

message MJobs {
    optional string name = 1;
    optional EJobStatus status = 2;
}`

should fix.

**Comment by hjagodzinski** [comment]
The compiler still should be able to parse it. Fixed in #74.
