### ISSUE TITLE
Error when compiling: requires protobuf extension installed to run

### ISSUE THREAD

**Issue by sbtdkj1017** [allegro/php-protobuf#47]
When executing "php protoc-php.php test.proto", I got such output:
protoc-php.php requires protobuf extension installed to run

**Comment by codycoder** [comment]
I get this too.  

php -m doesn't show the module is loaded.

web@server:~/php-protobuf-master$ sudo make install
Installing shared extensions:     /usr/lib/php5/20121212/
web@server:~/php-protobuf-master$ sudo nano /etc/php5/apache2/php.ini

from php.ini:

extension_dir=/usr/lib/php5/20121212
extension=/usr/lib/php5/20121212/protobuf.so

nothing bad in /var/log/apache2/error.log upon apache restart.

**Comment by PunitSaharan** [comment]
Hi please help me i want to install php-protobuf in xamp on window.but i have no idea how it will be installed .when i run protoc-php.php its show "requires protobuf extension installed to run". how can i install this extension ??

Thanks

**Comment by codycoder** [comment]
For me (and I can't say it will be the same with XAMPP on Windows - I always use Linux) but I realized that I needed to make sure I had loaded the protobuf extension in the command line PHP interpreter as well as the CGI.

If, on the command line you do: "php -m" you should see an alphabetized list of the loaded extensions. If you do not see the protobuf extension you need to find the PHP.ini file the command line interpreter uses (which is not the same path as the regular INI file) and just add the same details for the protobuf extension to it. 

Reload Apache and then once you check with "php -m" and see the loaded extension you should be all set.

**Comment by spartan092** [comment]
Hi I have a problem when i use   php protoc-php.php foo.proto:
protoc-php.php requires protobuf extension installed to run

**Comment by codycoder** [comment]
@spartan092 Did you see the comment above?

**Comment by spartan092** [comment]
When i use php-protobuf $ sudo make install
make: *** No rule to make target `install'.  Stop.

**Comment by codycoder** [comment]
I feel you must have missed at least one important step.  The complete procedure you've used so far hasn't been posted so I'm guessing at this stage.

I've attached an edited version of the step document I use in our environments.  ALl I removed was information specific to our development environment. 

If you:

* install the prerequisite packages and libraries (there's a few supporting systems you need)
* install a LAMP stack (at least Apache with PHP support and command line support in BOTH php.ini files (totally essential) - there is one for CLI support and one for the CGI module for Apache.
* have error free compiling after "phpize", "confugure",  "make" and "make install"
* edit both PHP ini files and you see the protobuf extension when you call _phpinfo()_ from a web page and also when you do _php -m_ on the command line, then: 

Things _should_ work out ;)

I'm not sure what your physical environment is, but if you're working with a virtual machine, sometimes it's worth it to just start fresh.

Best of luck.

[protobuf.md.pdf](https://github.com/allegro/php-protobuf/files/100187/protobuf.md.pdf)

**Comment by tonyliu-minted** [comment]
@sbtdkj1017 did you do autoconf first to generate all the make files?

**Comment by tonyliu-minted** [comment]
@spartan092 ^^

to be clearer
```
autoconf
./configure
make
sudo make install
```
add extension to php.ini file.

**Comment by sbtdkj1017** [comment]
@tonyliu-minted , after "add extension to php.ini file", it works.
Thanks for reply
