### ISSUE TITLE
Resolve imports dependency paths?

### ISSUE THREAD

**Issue by codycoder** [allegro/php-protobuf#49]
I am attempting to compile some .proto files for a large project our company is working on and many of their .proto files have large numbers of `import` statements which refer to other .proto files outside the current directory.

The `drslump` library looks like it has a -i statement which allows you to tell `protoc` to look in other directories for dependent files.

I called protoc-php.php with no options and this is what it said:

USAGE: protoc-php.php [OPTIONS] PROTO_FILE
  -n, --use-namespaces              Use native PHP namespaces
  -p, --filename-prefix [PREFIX]    Specify a prefix for generated file names
  --psr                             Output class files in a psr-4 directory structure

**Comment by tttlh** [comment]
+1

**Comment by codycoder** [comment]
We ended up moving all the .proto files the vendor provided (which they had all sorted in directories - by function) into the a single folder. Fortunately there were no duplicate file names to worry about.  This solved the problem for us.

**Comment by christophermancini** [comment]
@codycoder FYI, my fork of this project has many upgrades to the compiler. I haven't added support for alternate directories to check but it is something that can probably be added. The maintainers of this project have not been active in many months. 

https://github.com/christophermancini/php-protobuf/blob/master/bin/protoc#L71

**Comment by codycoder** [comment]
Yeah I know the Allegro library doesn't seem to be very active. It's a bit of a concern since the project we are working on requires protobuf use and php.  Thanks for this information, I'll check it out.

**Comment by christophermancini** [comment]
Yea, that is why I started working on it because it was the closest to meeting our needs for the Basho Riak PHP client. Whether they come back or not, we will be continuing to develop the lib.
