### ISSUE TITLE
Anyone recognize this error (RedHat)

### ISSUE THREAD

**Issue by yanelev** [allegro/php-protobuf#55]
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20121212/protobuf.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20121212/protobuf.so: undefined symbol: zend_get_hash_value in Unknown on line 0

**Comment by markvdlaan** [comment]
I have the same problem:

PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/plesk/php/5.6/lib64/php/modules/protobuf.so' - /opt/plesk/php/5.6/lib64/php/modules/protobuf.so: undefined symbol: zend_get_hash_value in Unknown on line 0
