### ISSUE TITLE
How to install php-protobuf  in xamp (Window) .

### ISSUE THREAD

**Issue by PunitSaharan** [allegro/php-protobuf#56]
Hi please help me i want to install php-protobuf in xamp on window.but i have no idea how it will be installed .when i run protoc-php.php its show "requires protobuf extension installed to run". how can i install this extension ??

Thanks

**Comment by mrjoebudi** [comment]
try this
https://github.com/chobie/php-protocolbuffers/wiki/Tutorial

**Comment by PunitSaharan** [comment]
@mrjoebudi  its show "phpize is not recognized as an internal or external command ??

**Comment by Gielert** [comment]
I have compiled the binaries to both thread safe and non-thread safe. I don't know if you still need them but here they are anyway.

https://www.dropbox.com/s/3d9g9ozxq0z9h3x/php-protobuf_x86.zip?dl=0

Binaries are compiled for PHP 5.6 x86

Here's the virustotal:
https://www.virustotal.com/en/file/22be40d7acb4eb43a4a14205d68726bba4e6de66a367f65566029d349e365825/analysis/1451938893/

SHA256: 22be40d7acb4eb43a4a14205d68726bba4e6de66a367f65566029d349e365825

**Comment by insthync** [comment]
@Gielert  You've wrote new config.w32 right? If yes can I see your config.w32 script? :)

**Comment by Gielert** [comment]
```
ARG_ENABLE("protobuf", "whether to enable protobuf support","no");

if(PHP_PROTOBUF != "no") {
	AC_DEFINE("HAVE_PROTOBUF", 1, "Whether you have protobuf extension");
	EXTENSION("protobuf", "protobuf.c reader.c writer.c", true);
}
````
Here you go :D

**Comment by TryCatchLoop** [comment]
How can I intall DLLs Gilbert? Help Please!

**Comment by dswtech** [comment]
@Gielert can you please build for php5.6 64bit please, And I need curve25519 too

**Comment by Gielert** [comment]
Sure thing. I will try to build the 64bit versions.

**Comment by kadnan** [comment]
@Gielert can I use on OSX 64 bit? please guide

**Comment by Gielert** [comment]
If you're on osx, you could just follow the original install guide. You
should have installed PHP and compilers. This can be accomplished with
homebrew for mac.

**Comment by kadnan** [comment]
@Gielert I am using MAMP. Are you suggesting to install `php-protobuf` via Brew?

**Comment by Gielert** [comment]
Try this: http://verysimple.com/2013/11/05/compile-php-extensions-for-mamp/

**Comment by oneleft** [comment]
@Gielert Did you ever compile an x64 version for 5.6 XAMP?

**Comment by Gielert** [comment]
@oneleft @dswtech As per request, I have compiled the x64 versions as well. Both the Thread-safe and Non Thread-safe are in the zip.

https://www.dropbox.com/s/lfhox1rm80xidw6/php-protobuf_x64.zip?dl=0

Here's the virustotal:
https://www.virustotal.com/nl/file/2a09a2e4259379d228c73ee0b1c524132b79fdc80d11b0ac96ee39c38efdb854/analysis/1463844140/

SHA256: 2a09a2e4259379d228c73ee0b1c524132b79fdc80d11b0ac96ee39c38efdb854

**Comment by kimkcc** [comment]
@Gielert Did you latest compile x86 and x64 ..  .. thank you if you have it

**Comment by longandy** [comment]
不错

**Comment by HSN-ALJ** [comment]
is it still working for XAMP ?

im trying to setup chat api but it is not working for me,
I have a 32 bit environment and I've done the below:
1- update the chat api package to receive the WA Password (fix 'old version' issue)
2- downloaded the dlls you share and place it in the xamp/php/ext folder
3- edit php.ini & add extention=protobuf & extention=curve25519

but still not able to connect to google to get the contact numbers & not able to send Whatsapp 

could you please help ?

**Comment by bcashier** [comment]
@Gielert Hi sir,

Any compiled version for PHP7.2.7 and x64 ? Windows 7.

Thank you
