### ISSUE TITLE
Can't find generated file

### ISSUE THREAD

**Issue by kadnan** [allegro/php-protobuf#61]
When running command:
```
php protoc-php.php MyFile.proto
```

it runs and does nothing. Where the files are being generated?

**Comment by hjagodzinski** [comment]
The generated file should be in the same directory as **MyFile.proto**.

**Comment by lsjun** [comment]
I had this issue too

**Comment by lsjun** [comment]
@kadnan @hjagodzinski Files are hidden

**Comment by lovelock** [comment]
@lsjun This confused me, too. When I open the directory with sublimetext, I finally find the hidden file.

**Comment by hjagodzinski** [comment]
Fixed in #60
