### ISSUE TITLE
Makefile:193: recipe for target 'protobuf.lo' failed

### ISSUE THREAD

**Issue by willgrnr** [allegro/php-protobuf#76]
Getting this when using $make. Makefile seems to be having a lot of problems.

https://gist.github.com/willgrnr/9376bd141506845d16935df1a4c44aa9

**Comment by serggp** [comment]
@willgrnr Looks like you were trying to compile it for php7. Current version supports php5 only. Php7 support is implemented in pull request https://github.com/allegro/php-protobuf/pull/63

**Comment by willgrnr** [comment]
@serggp that'll do it. However I'm getting the following when using: $ php protoc-gen-php.php stats.proto

`ERROR: protobuf module is not installed.`

**Comment by hjagodzinski** [comment]
@willgrnr it means what it says, the module is not installed 😉  In order to be able to run the compiler you need to install php-protobuf extension.

**Comment by willgrnr** [comment]
I'll have a go at reinstalling, must have mucked something somewhere. Thanks @hjagodzinski @serggp
