### ISSUE TITLE
it's too hard to compile dll in windows!

### ISSUE THREAD

**Issue by whysohandsome** [allegro/php-protobuf#79]
who can give me the dll compiled? i'm try it for few days,but i'm failed;
PHP Version 5.5.12 
MSVC11 (Visual C++ 2012)
x64 
whysohandsome@qq.com
thank you!

**Comment by hjagodzinski** [comment]
@Gielert are you able to help out here? I recall you were able to build the extension for Windows. It would be great if I could put compiled extension as a part of the [0.11.0](https://github.com/allegro/php-protobuf/releases/tag/v0.11.0) release so others can easily find it.

**Comment by Gielert** [comment]
Sure, i'll take a look at it.

**Comment by hjagodzinski** [comment]
Great, thanks!

**Comment by hjagodzinski** [comment]
@whysohandsome have you tried binaries from #4?

**Comment by hjagodzinski** [comment]
Closing due to the lack of response.
