### ISSUE TITLE
Problem with nested messages

### ISSUE THREAD

**Issue by swapniel99** [allegro/php-protobuf#80]
Hi,

How to use nested messages?
For example i have the following proto:

```
message Foo
{
    required int32 bar = 1;
    optional string baz = 2;
    repeated float spam = 3;

    message Sub
    {
        optional int64 id = 1;
        optional int32 age_sec = 2;
    }
}

```
Using protoc-gen-php.php makes two php Files: Foo.php and Foo_Sub.php
And Foo.php has no mention of sub anywhere. How to deal with this?

**Comment by hjagodzinski** [comment]
There is no mention about this class because it's not needed 😉  What's the exact issue you're dealing with?

**Comment by swapniel99** [comment]
How to deserialize suc a message, can you please give an example?

**Comment by hjagodzinski** [comment]
Take a look at [Usage](https://github.com/allegro/php-protobuf#usage).

**Comment by swapniel99** [comment]
Your hints and clues won't work because I am not a PHP programmer. Usage doesn't show the nested case I am asking about.

Please tell me how to create such a PHP object and serialize it. How to deserialize it. How to include multiple php files generated.

**Comment by hjagodzinski** [comment]
The only difference the nested case implies is different class name, nothing more. Please find an example for your case but it doesn't show much more than the Usage section.

```php
require_once 'Foo_Sub.php';

$fooSub = new \Foo_Sub();
$fooSub->setId(1);
$fooSub->setAgeSec(2);
$packed = $fooSub->serializeToString();

$unpackedSubFoo = new \Foo_Sub();
$unpackedSubFoo->parseFromString($packed);
$unpackedSubFoo->dump();
```

**Comment by swapniel99** [comment]
This I was able to do before. But don't we need to add $fooSub to $foo somehow?
So that we get a single packed string.

**Comment by hjagodzinski** [comment]
You don't have a field of type Sub in Foo message..

**Comment by swapniel99** [comment]
Yes.. But shouldn't there be? The example you gave simply deals with Foo_Sub.
Not the entire Foo. How to do that?

**Comment by hjagodzinski** [comment]
No, I don't need to define a field of nested type, it's up to you but basically you define nested messages to use them in a parent message.
