### ISSUE TITLE
Empty objects

### ISSUE THREAD

**Issue by socketman2016** [allegro/php-protobuf#82]
In this proto
```
message MyProto {
    User user = 1;
    float id = 2;
}
```

If I create new object of MyProto  and set user and empty User object , when I printDebugString , Ican see empty object in user property
But if I serializeToString and parseFromString and then printDebugString , there is no  empty object  and user is null
Why? How can I pass empty object ?

**Comment by serggp** [comment]
Could you please clarify what do you mean when you say 'empty User object'?

**Comment by socketman2016** [comment]
Assume we have this proto and compile it
```
message User{
      string name = 1;
      string family= 2;
}
```

the empty user object is 
```
$user = new User;
```

not empty user object is 
```
$user = new User;
$user->setName('Joe');
```

**Comment by amereii** [comment]
Any idea?

**Comment by socketman2016** [comment]
Any idea?

**Comment by hjagodzinski** [comment]
During serialization empty objects are skipped. I agree with point that you have different object state after parsing which shouldn't be the case. I will fix it.

**Comment by serggp** [comment]
@hjagodzinski Skipping such objects during serialization is ok. This object should be recreated based on default values during parseFromString().

**Comment by serggp** [comment]
So I checked C++ implementation and fixed serialization method using the same approach. See pull request https://github.com/allegro/php-protobuf/pull/87
