### ISSUE TITLE
Issue on default values

### ISSUE THREAD

**Issue by ancuop** [allegro/php-protobuf#89]
I made a simple usage, it runs to Segmentation fault (core dumped). Could you please help to debug this case. If I remove the default values in file test.proto, it runs well. So I guess core dump is caused by the default. My test is as below:

test.proto
++++++++++++++++++++++++++++
syntax = "proto2";
message Foo
{
    required string id = 1;
	optional int32 at = 2 [default = 2];
	optional int32 tmax = 3 [default = 120];
}
++++++++++++++++++++++++++++

test.php
++++++++++++++++++++++++++++
<?php
ini_set('include_path', '.');
require_once 'test1/Foo.php';

function benchmark() {
     $data = new Foo();
     $data->setId(1608151000000001);
     $data->setAt(1397808490);
     $data->setTmax(1398219351);
}

$totalTime = 0;
for($x = 0; $x <2000; $x++) {
	$totalTime += 1;
	echo $totalTime;
	echo "\n";
	benchmark();
}
?>
++++++++++++++++++++++++++++

The output result is:
++++++++++++++++++++++++++++
1
2
Segmentation fault (core dumped)
++++++++++++++++++++++++++++

**Comment by hjagodzinski** [comment]
Unfortunately there is a bug. I already have a working fix but before I create a pull request I would like to make few tests.

**Comment by ancuop** [comment]
@hjagodzinski
Thank you very much, hope get bug fix soon!

**Comment by hjagodzinski** [comment]
@ancuop should be better now. Thanks for reporting!
