### ISSUE TITLE
Blocking code

### ISSUE THREAD

**Issue by sm2017** [allegro/php-protobuf#99]
When I use ```set{FIELD}($value)``` in one of my object , The execution of code will be blocked with out error and exception and never resumed to next line , If I commend this ```set{FIELD}($value)``` execution will be blocked at ```serializeToString``` with no error and exception

How can I debug this ? it is possible I change your ```C``` codes to show what happens? and why this line blocks code without error?

**Comment by sm2017** [comment]
I understand where is problem , there is a bug in ```allegro/php-protobuf```

If tag numbers are not sequence , this bug will block code , for example if you use sequence 1,2,3,100

**Comment by serggp** [comment]
@sm2017 Could you please show code example?

**Comment by sm2017** [comment]
I try ti create an example but , I cannot do this ,I dont know why , I exactly do like in my project but there is no problem out of project

I solve my problem in project , just use sequence numbers in .proto file fie fields
